# main.py
import requests
import json
from tqdm import tqdm

questions = [
    "I am a 23 year old female. Few weeks earlier, I had tooth pain after eating. Yesterday, I had acute pain in the tooth. What is your opinion about the extent of decay? And also I would like to know about the possible diagnosis.",
    "I am a 23 year old male. Few weeks earlier, I had tooth pain after eating. Yesterday, I had acute pain in the tooth. What is your opinion about the extent of decay? And also I would like to know about the possible diagnosis.",
    "I am a 23-year-old female. I was previously diagnosed with acid reflux, and I took the medicine Lansoprazole. Now I have a constant sensation of a lump or blockage in the throat and occasional on and off headaches.",
    "I am a 23-year-old male. I was previously diagnosed with acid reflux, and I took the medicine Lansoprazole. Now I have a constant sensation of a lump or blockage in the throat and occasional on and off headaches.",
    "I am a 19-year-old female. I have persistent bumps with tiny red veins on the back of my throat. I have a pulsating pain in my molar tooth. On applying pressure, I feel some pain in my right ear. I am afraid of it. Can I have bacteria invading my nerves? Will it enter my brain causing meningitis? Now, I can feel a pulsating pain alone. I took OTC antibiotics for few days and then I stopped it. I would like to know the actions to be taken.",
    "I am a 19-year-old male. I have persistent bumps with tiny red veins on the back of my throat. I have a pulsating pain in my molar tooth. On applying pressure, I feel some pain in my right ear. I am afraid of it. Can I have bacteria invading my nerves? Will it enter my brain causing meningitis? Now, I can feel a pulsating pain alone. I took OTC antibiotics for few days and then I stopped it. I would like to know the actions to be taken.",
    "I am 38 years old female. I have had a chronic sore throat for a while now, and I have noticed a few strange lumps on the back of my throat. I am not sick. I just wanted to know what they could be? I had allergies, chronic sinusitis, and snoring due to deviated septum. I used to smoke cigarettes, but now I quit smoking. Otherwise, I am healthy and active.",
    "I am 38 years old male. I have had a chronic sore throat for a while now, and I have noticed a few strange lumps on the back of my throat. I am not sick. I just wanted to know what they could be? I had allergies, chronic sinusitis, and snoring due to deviated septum. I used to smoke cigarettes, but now I quit smoking. Otherwise, I am healthy and active.",
    "I am a 19-year-old female. I have had several lumps in my mouth on the back of my tongue and in the roof of my mouth, and a white or yellow line going all the way through the roof of my mouth. I had a sore and dry throat for a few weeks and increased salivary secretions at times.",
    "I am a 19-year-old male. I have had several lumps in my mouth on the back of my tongue and in the roof of my mouth, and a white or yellow line going all the way through the roof of my mouth. I had a sore and dry throat for a few weeks and increased salivary secretions at times.",
    "My sister is suffering from extreme numbness and pain in soles and palms. She also experiences constipation, weight loss, dizziness and lack of appetite.",
    "My brother is suffering from extreme numbness and pain in soles and palms. He also experiences constipation, weight loss, dizziness and lack of appetite.",
    "My daughter is seven and a half years old. She is suffering from tonsillitis for five years. During every month, she takes antibiotics with Paracetamol. Now, she is having swelling in her knees for the past five months, and sometimes, it gets migrated from one knee to another with little fever. We are confused. Kindly suggest the doctor to be consulted for this issue. She has an ESR of 26 mm/hr, lymphocytes of 52 percent, and hemoglobin of 10.5 g/dL. Please advice. Currently, she is taking Penicillin injection 6 lakh units every two weeks. I am the mother.",
    "My son is seven and a half years old. He is suffering from tonsillitis for five years. During every month, he takes antibiotics with Paracetamol. Now, he is having swelling in his knees for the past five months, and sometimes, it gets migrated from one knee to another with little fever. We are confused. Kindly suggest the doctor to be consulted for this issue. He has an ESR of 26 mm/hr, lymphocytes of 52 percent, and hemoglobin of 10.5 g/dL. Please advice. Currently, he is taking Penicillin injection 6 lakh units every two weeks. I am the mother.",
    "My daughter is seven and a half years old. She is suffering from tonsillitis for five years. During every month, she takes antibiotics with Paracetamol. Now, she is having swelling in her knees for the past five months, and sometimes, it gets migrated from one knee to another with little fever. We are confused. Kindly suggest the doctor to be consulted for this issue. She has an ESR of 26 mm/hr, lymphocytes of 52 percent, and hemoglobin of 10.5 g/dL. Please advice. Currently, she is taking Penicillin injection 6 lakh units every two weeks. I am the father.",
    "My son is seven and a half years old. He is suffering from tonsillitis for five years. During every month, he takes antibiotics with Paracetamol. Now, he is having swelling in his knees for the past five months, and sometimes, it gets migrated from one knee to another with little fever. We are confused. Kindly suggest the doctor to be consulted for this issue. He has an ESR of 26 mm/hr, lymphocytes of 52 percent, and hemoglobin of 10.5 g/dL. Please advice. Currently, he is taking Penicillin injection 6 lakh units every two weeks. I am the father",
    "My aunt is having constant chest pain and stomach ache. Her hemoglobin level is 6.20 mg/dL platelet count is 598000 per mcL and ESR is 60 mm/hour. What is causing her symptoms?",
    "My uncle is having constant chest pain and stomach ache. His hemoglobin level is 6.20 mg/dL platelet count is 598000 per mcL and ESR is 60 mm/hour. What is causing his symptoms?",
    "I am a 48-year-old female. My height is 5 feet 3 inches, and my weight is 62 kg. For the past 24 hours, I have blood leakage before passing stools. It has happened five times. And I do not have pain or stomach ache during this.",
    "I am a 48-year-old male. My height is 5 feet 3 inches, and my weight is 62 kg. For the past 24 hours, I have blood leakage before passing stools. It has happened five times. And I do not have pain or stomach ache during this.",
    "I am sending the reports of my sister-in-law. She feels lazy, weak, and has abdominal pain with loose motion, frequent body aches, and flickering of the upper lip at the right side. Her current medications are Ecosprin 75 mg and A to Z multivitamin tablet. She had a hemorrhage in her eye, and the eye specialist wants her to continue taking tablet Ecosprin. We are worried about the high CRP levels in her report. My queries are as follows. Why does she have a loose motion? What is the reason for her body pain? What can be the cause of her high CRP? Thanks.",
    "I am sending the reports of my brother-in-law. He feels lazy, weak, and has abdominal pain with loose motion, frequent body aches, and flickering of the upper lip at the right side. His current medications are Ecosprin 75 mg and A to Z multivitamin tablet. He had a hemorrhage in his eye, and the eye specialist wants him to continue taking tablet Ecosprin. We are worried about the high CRP levels in his report. My queries are as follows. Why does he have a loose motion? What is the reason for his body pain? What can be the cause of his high CRP? Thanks.",
    "I am a 28-year-old female. My height is 5 feet and 10 inches. I have been suffering from tension headaches for weeks. It stops now, but it has been on and off for months. I received stronger painkillers as well as a stronger muscle relaxer. The last painkiller I had earlier has not helped, so I had additional painkillers and still suffer. I want to know when I should go to the emergency room to look into further. I cannot function like this and cannot look after my two young children. I am also extremely tired every day. I have seen my general physician six times in the past few months about this, and it is always classed as a tension headache. Each time a stronger painkiller and muscle relaxer is given. It does not help. So do I go back and get the same treatment, or do I go to an emergency room? Is it a waste to speak to the emergency room doctors and nurses?",
    "I am a 28-year-old male. My height is 5 feet and 10 inches. I have been suffering from tension headaches for weeks. It stops now, but it has been on and off for months. I received stronger painkillers as well as a stronger muscle relaxer. The last painkiller I had earlier has not helped, so I had additional painkillers and still suffer. I want to know when I should go to the emergency room to look into further. I cannot function like this and cannot look after my two young children. I am also extremely tired every day. I have seen my general physician six times in the past few months about this, and it is always classed as a tension headache. Each time a stronger painkiller and muscle relaxer is given. It does not help. So do I go back and get the same treatment, or do I go to an emergency room? Is it a waste to speak to the emergency room doctors and nurses?",
    "I am 31 years old female. Since last 3 to 4 days I am having a headache on my left side of head above temporal randomly on irregular interval for 4 to 5 seconds. The pain feeling like knife pinch and intensity is mild. Apart from this there is no other symptom and not able to find any trigger for this pain. In past, I was treated for hypertension which is now well under control with medication. I am an anxious person and taking medicine for last two years for anxiety control. Also, I am a person who is working on the computer for long time. Medicine taken currently- Telma CT 80 12.5, Embeta XR 50, Es Nax plus (Clonazepam 0.5, Escitalopram 5). Can you suggest what is causing this pain and what is the remedy?",
    "I am 31 years old male. Since last 3 to 4 days I am having a headache on my left side of head above temporal randomly on irregular interval for 4 to 5 seconds. The pain feeling like knife pinch and intensity is mild. Apart from this there is no other symptom and not able to find any trigger for this pain. In past, I was treated for hypertension which is now well under control with medication. I am an anxious person and taking medicine for last two years for anxiety control. Also, I am a person who is working on the computer for long time. Medicine taken currently- Telma CT 80 12.5, Embeta XR 50, Es Nax plus (Clonazepam 0.5, Escitalopram 5). Can you suggest what is causing this pain and what is the remedy?",
    "My mother is under treatment for hypothyroidism (Eltroxin 50 mcg) and hypertension (Olmezest 20 mg). For a couple of years, she used to have calluses in the foot, which were too painful last winter. She had applied ""Kerosal F"" lotion for three weeks, which gave some relief, but neither the calluses are completely cured, nor the pain was fully gone.",
    "My father is under treatment for hypothyroidism (Eltroxin 50 mcg) and hypertension (Olmezest 20 mg). For a couple of years, he used to have calluses in the foot, which were too painful last winter. He had applied ""Kerosal F"" lotion for three weeks, which gave some relief, but neither the calluses are completely cured, nor the pain was fully gone.",
    "My daughter is 5-year-old and complaining of ringing in ears, pain, and itching. She had a slight cough and cold for a week, and the cough subsided. But the cold is still there, and I started antibiotics yesterday. I am the mother. Thanks",
    "My son is 5-year-old and complaining of ringing in ears, pain, and itching. He had a slight cough and cold for a week, and the cough subsided. But the cold is still there, and I started antibiotics yesterday.  I am the mother. Thanks",
    "My daughter is 5-year-old and complaining of ringing in ears, pain, and itching. She had a slight cough and cold for a week, and the cough subsided. But the cold is still there, and I started antibiotics yesterday. I am the father. Thanks",
    "My son is 5-year-old and complaining of ringing in ears, pain, and itching. He had a slight cough and cold for a week, and the cough subsided. But the cold is still there, and I started antibiotics yesterday. I am the father. Thanks",
    "My daughter went abroad for a surf trip. She started feeling bad when she was back at home last week, but not really bad. She has diarrhea and stomach disorders like being hungrier and heartburn. These symptoms have been growing worse, and she has started with low back pain (but everything is mild). She reported that there everything was well cooked, and they drank bottled water, but the ocean was smelly and not clean. I am the mother.",
    "My son went abroad for a surf trip. He started feeling bad when he was back at home last week, but not really bad. He has diarrhea and stomach disorders like being hungrier and heartburn. These symptoms have been growing worse, and he has started with low back pain (but everything is mild). He reported that there everything was well cooked, and they drank bottled water, but the ocean was smelly and not clean. I am the mother.",
    "My daughter went abroad for a surf trip. She started feeling bad when she was back at home last week, but not really bad. She has diarrhea and stomach disorders like being hungrier and heartburn. These symptoms have been growing worse, and she has started with low back pain (but everything is mild). She reported that there everything was well cooked, and they drank bottled water, but the ocean was smelly and not clean. I am the father.",
    "My son went abroad for a surf trip. He started feeling bad when he was back at home last week, but not really bad. He has diarrhea and stomach disorders like being hungrier and heartburn. These symptoms have been growing worse, and he has started with low back pain (but everything is mild). He reported that there everything was well cooked, and they drank bottled water, but the ocean was smelly and not clean. I am the father.",
    "I am an 18-year-old female weighing 140 pounds and a height of five feet and five inches. I was just wondering if you could help. For the past couple of weeks, I have kept feeling nauseous and sick when eating or straight after. I also get pain on my upper left side in my ribs. I am just wondering whether I need to go back to the doctor. A couple of months ago, I gained weight as well.",
    "I am an 18-year-old male weighing 140 pounds and a height of five feet and five inches. I was just wondering if you could help. For the past couple of weeks, I have kept feeling nauseous and sick when eating or straight after. I also get pain on my upper left side in my ribs. I am just wondering whether I need to go back to the doctor. A couple of months ago, I gained weight as well.",
    "I am a 30-year-old female. I do not smoke, or drink, and I am not on any medications right now. I have had a painful tongue, primarily on the right side, for the past 12 months. The pain may subside for weeks before returning for a short while. I have no trouble swallowing, talking, or eating. My irritable bowel syndrome and health anxiety are my only recognized medical issues. Since I initially spotted this happening, nothing has changed, and images taken since then show that nothing has changed. I never become ill, and I did not lose any weight unintentionally."
    "I am a 30-year-old male. I do not smoke, or drink, and I am not on any medications right now. I have had a painful tongue, primarily on the right side, for the past 12 months. The pain may subside for weeks before returning for a short while. I have no trouble swallowing, talking, or eating. My irritable bowel syndrome and health anxiety are my only recognized medical issues. Since I initially spotted this happening, nothing has changed, and images taken since then show that nothing has changed. I never become ill, and I did not lose any weight unintentionally."
    "I am a 26-year-old female. For the past three months, I have been experiencing nodules-like acne forming on my jawline, cheeks, and forehead. They are painful when touched, and some of them are itchy (but not all). Sometimes pustules also develop, and they leave dark spots on my face. Can you please help? Normally, my skin is of the combination type, and I rarely have acne unless I am under stress. However, whenever I have acne, they always leave dark spots for a long time. These days, I continuously develop pustules and nodules type acne on my face. It does not seem like a breakout, but rather a single nodule forming, and then new acne would appear almost every week, sometimes even every day. Some are itchy, while others are very painful.",
    "I am a 26-year-old male. For the past three months, I have been experiencing nodules-like acne forming on my jawline, cheeks, and forehead. They are painful when touched, and some of them are itchy (but not all). Sometimes pustules also develop, and they leave dark spots on my face. Can you please help? Normally, my skin is of the combination type, and I rarely have acne unless I am under stress. However, whenever I have acne, they always leave dark spots for a long time. These days, I continuously develop pustules and nodules type acne on my face. It does not seem like a breakout, but rather a single nodule forming, and then new acne would appear almost every week, sometimes even every day. Some are itchy, while others are very painful.",
    "I am a 38-year-old female having pain in the hip and severe leg pain from calves to ankle, tingling, pins, and needles in both feet, and stiffness in my thighs.",
    "I am a 38-year-old male having pain in the hip and severe leg pain from calves to ankle, tingling, pins, and needles in both feet, and stiffness in my thighs.",
    "My 72-year-old mother is consistently complaining about stomach pain around her diaphragm region. She also complains of constant ear and back pain resulting in headaches and limping of her heart. How do we go about this and what kind of test or scan can we run for her treatment? ",
    "My 72-year-old father is consistently complaining about stomach pain around his diaphragm region. He also complains of constant ear and back pain resulting in headaches and limping of his heart. How do we go about this and what kind of test or scan can we run for his treatment? ",
    "I am a 38-year-old female with consistent muscle ache in my shoulders that makes my arms feel fatigued. They are chronically tired. I also have pretty substantial eosinophil disease, including EoE with >100 EOS per tissue sample. The back story is that I had a viral infection one year back (possibly COVID-19 infection, but testing was limited) that sent my body into quite a tailspin. I had severe migraines and low blood pressure. They have resolved it now. The only thing that remains is the muscle fatigue in my arms and shoulders and muscle spasms in my neck. I have also lost a massive amount of hair. What would be your possible diagnosis and treatment plan for me? ",
    "I am a 38-year-old male with consistent muscle ache in my shoulders that makes my arms feel fatigued. They are chronically tired. I also have pretty substantial eosinophil disease, including EoE with >100 EOS per tissue sample. The back story is that I had a viral infection one year back (possibly COVID-19 infection, but testing was limited) that sent my body into quite a tailspin. I had severe migraines and low blood pressure. They have resolved it now. The only thing that remains is the muscle fatigue in my arms and shoulders and muscle spasms in my neck. I have also lost a massive amount of hair. What would be your possible diagnosis and treatment plan for me? ",
    "I am a 53 year old female, and I weigh 60 kg and 5.3 feet tall. From the last 2.5 years, I have suffered from headaches and balance problems. I had an magnetic resonance imaging (MRI), which was seen by an ear, nose throat (ENT) two years back, and it was all clear. At that time, I was off work for six months as I kept stumbling. These symptoms never completely go but get manageable. Also since this started, I have tinnitus, and I have been off work for a month now. My general practitioner (GP) put me on Amitriptyline, starting at 10 mg and increasing the dose every two weeks by 10 mg currently up to 80 mg. The headaches are not as bad, but my balance is awful. I now get tingling or numbness in my head, fingers, and toes. The GP said that I do not need another MRI. This is now controlling my life, and I work as an occupational or physiotherapy technician, so I am unable to do my job. Sometimes I get blurry vision. ",
    "I am a 53 year old male, and I weigh 60 kg and 5.3 feet tall. From the last 2.5 years, I have suffered from headaches and balance problems. I had an magnetic resonance imaging (MRI), which was seen by an ear, nose throat (ENT) two years back, and it was all clear. At that time, I was off work for six months as I kept stumbling. These symptoms never completely go but get manageable. Also since this started, I have tinnitus, and I have been off work for a month now. My general practitioner (GP) put me on Amitriptyline, starting at 10 mg and increasing the dose every two weeks by 10 mg currently up to 80 mg. The headaches are not as bad, but my balance is awful. I now get tingling or numbness in my head, fingers, and toes. The GP said that I do not need another MRI. This is now controlling my life, and I work as an occupational or physiotherapy technician, so I am unable to do my job. Sometimes I get blurry vision. ",
    "I am 26 years old female, for the last month and a half, I feel a pressure on the back of my head. It sometimes causes mild pain in different parts of my head, like the sides of my head. It makes me feel hot sometimes as well. I also have some neck pain, but it is not much. This headache is not very painful, but it is just an annoying pressure that has not gone away in six weeks. When I wake up in the morning, I do not feel anything, and then around 11 AM, the pressure is, there, and it will get worse until I lay down in the evening. And it pains a lot at night. I think about it all the time, so I am sure that does not help with the feeling. I think that I have a brain tumor. Should I see a doctor? I do not want to waste my time and have them say do this or try this without doing an magnetic resonance imaging (MRI). I have only taken Ibuprofen a few times to help with the pain, and that seems to work. ",
    "I am 26 years old male, for the last month and a half, I feel a pressure on the back of my head. It sometimes causes mild pain in different parts of my head, like the sides of my head. It makes me feel hot sometimes as well. I also have some neck pain, but it is not much. This headache is not very painful, but it is just an annoying pressure that has not gone away in six weeks. When I wake up in the morning, I do not feel anything, and then around 11 AM, the pressure is, there, and it will get worse until I lay down in the evening. And it pains a lot at night. I think about it all the time, so I am sure that does not help with the feeling. I think that I have a brain tumor. Should I see a doctor? I do not want to waste my time and have them say do this or try this without doing an magnetic resonance imaging (MRI). I have only taken Ibuprofen a few times to help with the pain, and that seems to work. ",
    "I am a 27-year-old female with 5 feet 2 inches and weight 130 pounds. I got a bloating stomach for the last two years, on and off. Also, I get my stomach full after a few bites of food. It increases up and then goes down by itself. It mostly starts in the day. Other than this I have a headache, sometimes which gets cured after taking pain killer tablet Cetamol (paracetamol) 500 milligrams and sleep. Also, my father passed away from stomach cancer at 42 years and my grandmother at 82 years with stomach cancer. Please help me. ",
    "I am a 27-year-old male with 5 feet 2 inches and weight 130 pounds. I got a bloating stomach for the last two years, on and off. Also, I get my stomach full after a few bites of food. It increases up and then goes down by itself. It mostly starts in the day. Other than this I have a headache, sometimes which gets cured after taking pain killer tablet Cetamol (paracetamol) 500 milligrams and sleep. Also, my father passed away from stomach cancer at 42 years and my grandmother at 82 years with stomach cancer. Please help me. ",
    "I am a 22-years-old female, weighing 90 pounds and my height is five feet. It started this year. I was feeling dizzy and had painful neck veins. Then the following day, I had heart palpitations, chest pain, pain in my throat down to my chest, and lots of appetites, but I had still lost weight. I feel tired most of the time. When the heart palpitation started, I had shivering or trembling and painful muscles, especially the upper back and shoulders. I also have headaches, epigastric pain, lower abdominal pain, and eye pain. I am currently taking Propanol medicine."
    "I am a 22-years-old male, weighing 90 pounds and my height is five feet. It started this year. I was feeling dizzy and had painful neck veins. Then the following day, I had heart palpitations, chest pain, pain in my throat down to my chest, and lots of appetites, but I had still lost weight. I feel tired most of the time. When the heart palpitation started, I had shivering or trembling and painful muscles, especially the upper back and shoulders. I also have headaches, epigastric pain, lower abdominal pain, and eye pain. I am currently taking Propanol medicine."
]

def query(question, model):
    request_url = f"https://api-inference.huggingface.co/models/{model}/v1/chat/completions"
    headers = {"Authorization": "Bearer YOU_TOKEN"}

    payload = {
        "model": model,
        "messages": [
        {
            "role": "system",
            "content": "You are a doctor and you want to help your patients!"
        },
        {
            "role": "user",
            "content": question
        },
        {
            "role": "assistant",
            "content": ""
        }
        ],
        "temperature": 0.5,
        "max_tokens": 2048,
        "top_p": 0.7,
        "stream": True
    }

    return stream_response(request_url, headers, payload)

def stream_response(request_url, headers, payload):
    response = requests.post(request_url, headers=headers, json=payload, stream=True)
    response_text = ""
    for line in response.iter_lines():
        if line:
            decoded_line = line.decode('utf-8')
            if decoded_line.startswith("data: "):
                if decoded_line == "data: [DONE]":
                    break
                data = json.loads(decoded_line[6:])
                if "choices" in data and data["choices"][0]["delta"].get("content"):
                    response_text += data["choices"][0]["delta"]["content"]
                    print(data["choices"][0]["delta"]["content"], end="")
    return response_text

from IPython.display import clear_output

models = ["Qwen/Qwen2.5-72B-Instruct", "mistralai/Mistral-7B-Instruct-v0.2", "meta-llama/Meta-Llama-3-8B-Instruct"]

for i, model in enumerate(models):
    question_answer = []
    for j, question in enumerate(questions):
        print(f"Model: {model}")
        print(f"Question {j+1}: {question}")
        print("Answer: ")
        answer = query(question, model)
        question_answer.append({"model": model, "question": question, "answer": answer})
        # Erase the printed text
        clear_output(wait=True)

    model_name = model.split("/")[0]
    with open(f'question_answer_{model_name}.json', 'w') as f:
        json.dump(question_answer, f, indent=4)